/*
Problem 45: Triangular, Pentagonal, and Hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/

package problems

import "github.com/zolrath/euler/util/ngon"

const ANSWER_045 = 1533776805

func Euler045() int {
	tris := ngon.TriangleGenerator(286)
	for {
		tnum := tris()
		if ngon.IsPentagon(tnum) && ngon.IsHexagon(tnum) {
			return tnum
		}
	}
	return 0
}
